export const ignoredElementOnTouch = {
    click: [
        ".geonet__region",
        ".team__controls",
        ".innopolis__controls",
        ".geonet__data-right",
        ".geonet__map",
        ".geonet__connector",
        ".geonet__popup",
        ".search-popup__close",
        ".options",
        // "#innopolis",
        "#outer-modal",
        ".contacts__data",
        ".partners__controls",
        "form",
        "#fake-map",
    ],
    drop: [
        // ".team__container",
        ".main-header",
        ".splide",
        ".innopolis__controls",
        ".geonet__data-right",
        // ".geonet__map",
        ".geonet__connector",
        ".geonet__popup",
        ".search-popup__close",
        ".options",
        // "#innopolis",
        "#outer-modal",
        ".contacts__data",
        ".partners__controls",
        "form",
    ],
}
